/**
* SPDX-License-Identifier: Apache-2.0
*
* Copyright 2025 Synaptics Incorporated
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/*********************    Autogenerated file. DO NOT EDIT *******************
 * Generated from class.tflite file.
 * Date: 2025-04-12 18:49:48.052526
 ***************************************************************************/

#include <cstddef>
#include <cstdint> 
#include "inference_attributes.hpp"
#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"
 
namespace model_flash {
    constexpr int kNumberOperators = 2;
    tflite::MicroMutableOpResolver<kNumberOperators> micro_op_resolver;
    static bool initialized = false;
    tflite::MicroOpResolver& get_resolver(void)
    {
	if (initialized == false)
	{ 
	    micro_op_resolver.AddEthosU();
	    micro_op_resolver.AddFullyConnected();
	    initialized = true;
	}
	return micro_op_resolver;
    }
} /* namespace model_flash */