var searchData=
[
  ['sample_20isr_0',['Sample ISR.',['../group__group__gpio__driver.html#GPIO_ISR',1,'']]],
  ['sd_20card_1',['SD Card',['../group__group__sdio__driver.html#group_sd_card',1,'']]],
  ['sd_20card_20configuration_20and_20initialization_2',['SDIO SD Card Configuration and Initialization.',['../group__group__sdio__driver.html#SDIO_SD_CARD_INIT',1,'']]],
  ['sd_20card_20read_20operation_3',['SDIO SD Card Read Operation.',['../group__group__sdio__driver.html#SDIO_READ_OPERATION',1,'']]],
  ['sd_20card_20write_20operation_4',['SDIO SD Card Write Operation.',['../group__group__sdio__driver.html#SDIO_WRITE_OPERATION',1,'']]],
  ['sdio_20direct_20i_20o_20transfer_20operation_20cmd52_5',['SDIO Direct I/O Transfer Operation (CMD52)',['../group__group__sdio__driver.html#SDIO_CMD52_OPERATION',1,'']]],
  ['sdio_20extended_20i_20o_20transfer_20operation_20cmd53_6',['SDIO Extended I/O Transfer Operation (CMD53)',['../group__group__sdio__driver.html#SDIO_CMD53_OPERATION',1,'']]],
  ['sdio_20host_20configuration_20and_20initialization_7',['SDIO Host Configuration and Initialization',['../group__group__sdio__driver.html#SDIO_CONFIG',1,'SDIO Host Configuration and Initialization.'],['../group__group__sdio__driver.html#SDIO_HOST_INIT_TEST',1,'SDIO Host Configuration and Initialization.']]],
  ['sdio_20i_20o_20device_20configuration_20and_20initialization_8',['SDIO I/O Device Configuration and Initialization.',['../group__group__sdio__driver.html#SDIO_DEVICE_INIT_TEST',1,'']]],
  ['sdio_20init_20operation_9',['SDIO Init Operation',['../group__group__sdio__driver.html#SDIO_INIT',1,'SDIO Init Operation'],['../group__group__sdio__driver.html#SDIO_INIT_IO',1,'SDIO Init Operation']]],
  ['sdio_20operations_10',['Cache Handling for SDIO Operations',['../group__group__sdio__driver.html#section11',1,'']]],
  ['sdio_20pinmux_20configuration_11',['SDIO Pinmux Configuration',['../group__group__sdio__driver.html#PINMUX_CONFIG',1,'']]],
  ['sdio_20sd_20card_20configuration_20and_20initialization_12',['SDIO SD Card Configuration and Initialization.',['../group__group__sdio__driver.html#SDIO_SD_CARD_INIT',1,'']]],
  ['sdio_20sd_20card_20read_20operation_13',['SDIO SD Card Read Operation.',['../group__group__sdio__driver.html#SDIO_READ_OPERATION',1,'']]],
  ['sdio_20sd_20card_20write_20operation_14',['SDIO SD Card Write Operation.',['../group__group__sdio__driver.html#SDIO_WRITE_OPERATION',1,'']]],
  ['sdk_20peripheral_20driver_20library_15',['Astra MCU SDK Peripheral Driver Library',['../index.html',1,'']]],
  ['sdr_20hdr_16',['Using Speed Modes (SDR/HDR)',['../group__group__i3c__driver.html#group_i3c_speed_modes',1,'']]],
  ['sections_17',['Sections',['../index.html#nav_sec',1,'']]],
  ['setting_20all_20electrical_20parameters_18',['Setting All Electrical Parameters',['../group__group__pinmux__driver.html#snippet_set_elec_config',1,'']]],
  ['setting_20pin_20function_19',['Setting Pin Function',['../group__group__pinmux__driver.html#snippet_set_function',1,'']]],
  ['setting_20target_20address_20',['Setting Target Address',['../group__group__i2c__driver.html#i2c_controller_set_target_address',1,'']]],
  ['single_20electrical_20parameter_21',['Getting a Single Electrical Parameter',['../group__group__pinmux__driver.html#snippet_get_elec_param',1,'']]],
  ['specific_20definitions_22',['2. &lt;b&gt;sr110_cm55.h&lt;/b&gt; (CM55-Specific Definitions)',['../md__r_e_a_d_m_e___s_t_r_u_c_t_u_r_e.html#autotoc_md9',1,'']]],
  ['speed_20modes_20sdr_20hdr_23',['Using Speed Modes (SDR/HDR)',['../group__group__i3c__driver.html#group_i3c_speed_modes',1,'']]],
  ['spi_24',['SPI',['../group__group__spi__driver.html#snippet_spi_controller_pinmux_config',1,'Controller PINMUX Configuration for SPI'],['../group__group__spi__driver.html#snippet_spi_peripheral_pinmux_config',1,'Peripheral PINMUX Configuration for SPI']]],
  ['sr110_20multi_20file_20documentation_20structure_25',['SR110 Multi-File Documentation Structure',['../md__r_e_a_d_m_e___s_t_r_u_c_t_u_r_e.html',1,'']]],
  ['sr110_5fcm55_20h_20cm55_20specific_20definitions_26',['2. &lt;b&gt;sr110_cm55.h&lt;/b&gt; (CM55-Specific Definitions)',['../md__r_e_a_d_m_e___s_t_r_u_c_t_u_r_e.html#autotoc_md9',1,'']]],
  ['sr110_5fgroups_20h_20main_20group_20definitions_27',['1. &lt;b&gt;sr110_groups.h&lt;/b&gt; (Main Group Definitions)',['../md__r_e_a_d_m_e___s_t_r_u_c_t_u_r_e.html#autotoc_md8',1,'']]],
  ['structure_28',['Structure',['../group__group__pinmux__driver.html#snippet_cfg_all',1,'Combined Configuration Structure'],['../group__group__pinmux__driver.html#snippet_elec_cfg',1,'Electrical Configuration Structure'],['../md__r_e_a_d_m_e___s_t_r_u_c_t_u_r_e.html#autotoc_md7',1,'File Structure'],['../md__r_e_a_d_m_e.html#autotoc_md4',1,'Folder Structure'],['../md__r_e_a_d_m_e___s_t_r_u_c_t_u_r_e.html',1,'SR110 Multi-File Documentation Structure']]],
  ['supported_20drivers_29',['Supported Drivers',['../index.html#drivers_sec',1,'']]]
];
