name: Process changes to documentation

on:
    workflow_dispatch:
    
    release:
        types: [published]

    push:
        branches:
            - main

    pull_request:
        types: [ opened, synchronize, closed ]

env:
    ACTIONS_STEP_DEBUG: true
    ACTIONS_RUNNER_DEBUG: true

jobs:

    process:
        name: Process

        permissions:
            actions: write
            contents: write
            pages: write
            id-token: write            

        uses: syna-astra-mcu-dev/action-doc-publish/.github/workflows/process.yml@v2
